# Generated by Django 4.2.7 on 2023-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatting", "0003_chatroom_conversation_chatroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="name",
            field=models.CharField(default="Chatroom", max_length=50),
        ),
    ]
